### ISSUE TITLE
Build failes under CentOS 7 after last commits

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-hangouts-attempt2#46]
**[Original report](https://bitbucket.org/EionRobb/purple-hangouts/issue/46) by Vitaly Zaitsev (Bitbucket: [xvitaly](https://bitbucket.org/xvitaly), GitHub: [xvitaly](https://github.com/xvitaly)).**

----------------------------------------

Build failes under CentOS 7 after commit c15d7f269a01a7167be3f931cd49bba2b5f016e8:

```
#!text
protoc-c --c_out=. hangouts.proto
protoc-c --c_out=. hangout_media.proto
cc -fPIC -shared -o libhangouts.so libhangouts.c hangouts.pb-c.c hangout_media.pb-c.c hangouts_json.c hangouts_pblite.c hangouts_connection.c hangouts_auth.c hangouts_events.c hangouts_conversation.c hangouts_media.c purple2compat/http.c purple2compat/purple-socket.c  -lprotobuf-c   `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`  -I/usr/include/protobuf-c -Ipurple2compat -g -ggdb
hangouts_media.c: In function 'hangout_get_session_media_type':
hangouts_media.c:141:35: error: 'PURPLE_MEDIA_APPLICATION' undeclared (first use in this function)
  } else if (purple_session_type & PURPLE_MEDIA_APPLICATION) {
                                   ^
hangouts_media.c:141:35: note: each undeclared identifier is reported only once for each function it appears in
hangouts_media.c: In function 'hangouts_media_candidates_prepared_cb':
hangouts_media.c:210:9: error: 'PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_PASSIVE' undeclared (first use in this function)
    case PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_PASSIVE:
         ^
hangouts_media.c:211:9: error: 'PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_ACTIVE' undeclared (first use in this function)
    case PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_ACTIVE:
         ^
hangouts_media.c:212:9: error: 'PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_SO' undeclared (first use in this function)
    case PURPLE_MEDIA_NETWORK_PROTOCOL_TCP_SO:
         ^
make: *** [libhangouts.so] Error 1
```
